

name: Cleanup Auto Branches

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  cleanup:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'chore/auto-update-catalog')
    runs-on: ubuntu-latest
    steps:
      - name: Delete head branch for catalog PRs
        uses: actions/github-script@v7
        with:
          script: |
            const ref = 'heads/' + context.payload.pull_request.head.ref;
            core.info(`Deleting ref: ${ref}`);
            await github.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref
            });